// WebRTC signaling server for `ay serve --share=webrtc://room:token@s.agent-yes.com`.
//
// One Durable Object per room relays SDP offers/answers + ICE candidates between
// the local `ay serve` peer (role=host) and one or more browser peers
// (role=client). It is a *rendezvous* only — media/data never flow through here,
// they go peer-to-peer over the WebRTC DataChannel once signaling completes.
//
// Auth: the room token is carried in the first WS message (NOT the URL, so it
// can't leak into request logs). The first peer to open a room fixes its token;
// every later peer must present the same token or it is rejected. The token is
// never logged.
//
// For the v2 (e2e) protocol the token a peer sends is `authToken = HKDF(S,…)`,
// NOT the URL secret S — so even a fully compromised server learns nothing it
// could use to read or inject traffic (the AES keys never leave the endpoints;
// see lab/ui/e2e.js). This DO additionally TOFU-pins the protocol version so an
// HONEST server fails a cross-generation join closed; that pin is a UX/migration
// aid only — the real confidentiality/integrity guarantees are client-enforced.

export interface Env {
  ROOMS: DurableObjectNamespace;
  EXPOSURES: DurableObjectNamespace;
  ASSETS: Fetcher;
}

export { Exposure } from "./exposure";

// Exposure subdomains: <id>.agent-yes.com (wildcard route). Ids are generated
// by `ay expose` and always start with "x", so they can never collide with
// named subdomains (s., www., …). See exposure.ts for the relay itself.
const EXPOSURE_HOST = /^(x[a-z0-9]{7,31})\.agent-yes\.com$/;

// The lab — design notes and write-ups (lab/ui/lab, generated by its build.ts
// into public/lab). It gets its own subdomain so the apex stays the product
// site, and it reaches this Worker through the EXISTING wildcard
// `*.agent-yes.com/*` route. Deliberately NOT added as a custom domain: the
// deploy token lacks Workers Routes:Edit (see TODO.md), so touching `routes`
// would break redeploys — and the wildcard already delivers this host.
const LAB_HOST = "lab.agent-yes.com";
const LAB_ORIGIN = `https://${LAB_HOST}`;

// /blog/* moved to the lab. The two posts that lived there keep working: their
// canonical URLs are now date-prefixed (the filenames in lab/ui/lab/posts/).
// Anything else under /blog lands on the lab index rather than a 404.
const BLOG_MOVED: Record<string, string> = {
  "ay-callback": "2026-07-22-ay-callback",
  "e2ee-share-links": "2026-06-15-e2ee-share-links",
};

const SUBPROTO = "ay-signal-1";

// Defense-in-depth CSP for the console document. The console renders agent
// metadata (terminal title / prompt / cwd) supplied by whatever host a share
// link points at — untrusted by definition — so even with output escaping we
// lock down where a hypothetical injection could send data. Blocks arbitrary
// fetch/beacon exfil (connect-src / img-src), plugins (object-src), <base>
// hijack (base-uri), clickjacking (frame-ancestors) and form exfil
// (form-action). script-src keeps 'unsafe-inline' because the console is a
// single-file inline app (no inline event-handler attributes exist, so a
// stricter nonce split is a follow-up, not a regression risk). The jsdelivr
// allowance in script-src/style-src is now ONLY for the rgui console at /r/
// (still CDN-loaded); the main /w/ console vendors xterm same-origin. Dropping
// jsdelivr is a follow-up gated on self-hosting rgui too (this CSP is global —
// _headers `/*` + every HTML response here — so removing it now would break /r/).
// 'unsafe-eval' exists for exactly one feature: user-authored `js:`
// quick commands (new Function over user-stored localStorage text — their own
// code in their own browser). connect-src allows any wss: so custom / self-hosted signaling hosts
// still work, while forbidding arbitrary https fetch exfil. Keep this in sync
// with the copy in ts/serve.ts (serveUiFile).
const CSP = [
  "default-src 'self'",
  "base-uri 'none'",
  "object-src 'none'",
  "frame-ancestors 'none'",
  "form-action 'self'",
  "img-src 'self' data:",
  "font-src 'self' data:",
  "style-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net",
  "script-src 'self' 'unsafe-inline' 'unsafe-eval' https://cdn.jsdelivr.net",
  "connect-src 'self' https://s.agent-yes.com https://agent-yes.com wss:",
  "worker-src 'self'",
  "manifest-src 'self'",
].join("; ");

// Heartbeat frames (host pings, server pongs). Defined once so the hibernation
// auto-response pair below matches the host's wire bytes EXACTLY — the runtime
// only auto-answers an incoming message that is byte-identical to PING.
const PING = JSON.stringify({ type: "ping" });
const PONG = JSON.stringify({ type: "pong" });

// Serve the console/lab documents and scripts with no-cache so a CDN/browser
// can't pin a stale client that predates a protocol upgrade — combined with the
// v:2 hello assertion, a stale client fails closed ("update required") rather
// than running an old wire. HTML additionally carries the CSP (the _headers file
// covers the same ground for assets served without the Worker in the path).
function withDocHeaders(res: Response): Response {
  const ct = res.headers.get("content-type") ?? "";
  if (!ct.includes("text/html") && !ct.includes("javascript")) return res;
  const h = new Headers(res.headers);
  h.set("Cache-Control", "no-cache");
  if (ct.includes("text/html")) h.set("Content-Security-Policy", CSP);
  return new Response(res.body, { status: res.status, statusText: res.statusText, headers: h });
}

// lab.agent-yes.com → the public/lab asset tree. The lab is generated FLAT
// (lab/ui/lab/build.ts writes `<date>-<slug>.html`), so a canonical post URL has
// no trailing slash and no extension; map it to its file explicitly rather than
// relying on the asset server's path normalization, which would answer with a
// redirect whose Location still carried the internal /lab prefix.
async function labFetch(url: URL, req: Request, env: Env): Promise<Response> {
  // Normalize the path before anything else looks at it. Two things matter here:
  //
  //   1. DUPLICATE SLASHES. Cloudflare does NOT collapse them, so `//evil.com/`
  //      arrives intact. A path in that shape is a PROTOCOL-RELATIVE URL
  //      reference, so resolving it against the request URL — `new URL(path, url)`
  //      — reuses the scheme but takes the AUTHORITY from the path, yielding
  //      https://evil.com/. That is an open redirect, cached by the browser
  //      because it is a 301, on a link that previews as agent-yes.com. Collapse
  //      first, and build the target by mutating a copy of the request URL
  //      (assigning .pathname never re-parses an authority) so the origin is
  //      structurally pinned rather than merely expected.
  //   2. A TRAILING SLASH, which would make a page's relative links (./slug, and
  //      the shared nav's ./) resolve against the wrong base.
  //
  // "/" is already canonical and never enters here (length > 1 guard); "//" and
  // friends collapse to "/", so the `|| "/"` keeps that from redirecting to "".
  const clean = url.pathname.replace(/\/{2,}/g, "/");
  if (clean !== url.pathname || (clean.length > 1 && clean.endsWith("/"))) {
    const to = new URL(url); // same origin by construction
    to.pathname = clean.replace(/\/+$/, "") || "/";
    return Response.redirect(to.toString(), 301);
  }
  // Ask the asset server for the path SHAPE the lab publishes — extensionless,
  // no trailing slash — not for the underlying `<slug>.html`. The assets config
  // treats extensionless as canonical (html_handling: auto-trailing-slash), so
  // `/lab/<slug>` is answered 200 from `<slug>.html`, while requesting the
  // `.html` form would earn a redirect BACK to `/lab/<slug>` — which, once the
  // /lab prefix is stripped below, is the URL the visitor already asked for.
  // That is an infinite redirect, and it is why this maps shape-to-shape.
  const inner = url.pathname === "/" ? "/lab/" : `/lab${url.pathname}`;
  const res = await env.ASSETS.fetch(new Request(new URL(`${inner}${url.search}`, url), req));
  if (res.status === 404) {
    return new Response(
      `<!doctype html><meta charset=utf-8><title>Not found — agent-yes lab</title>` +
        `<body style="font:16px/1.6 system-ui;max-width:40em;margin:12vh auto;padding:0 20px">` +
        `<h1>404</h1><p>No such note. <a href="/">All notes →</a>`,
      { status: 404, headers: { "content-type": "text/html; charset=utf-8" } },
    );
  }
  // Defensive: if the asset server ever does redirect, strip the internal prefix
  // so a visitor is never sent to lab.agent-yes.com/lab/<slug>.
  const loc = res.headers.get("location");
  if (loc && res.status >= 300 && res.status < 400) {
    const h = new Headers(res.headers);
    h.set("location", loc.replace(/^(https?:\/\/[^/]+)?\/lab(?=\/|$)/, "$1"));
    return new Response(null, { status: res.status, headers: h });
  }
  return withDocHeaders(res);
}

export default {
  async fetch(req: Request, env: Env): Promise<Response> {
    const url = new URL(req.url);

    // Route on the Host header (not url.hostname) so `wrangler dev` — where the
    // URL is always localhost — still resolves via a spoofed Host; in
    // production the two are identical.
    const host = req.headers.get("host") ?? url.hostname;

    // Visitor leg: EVERYTHING on an exposure subdomain belongs to its DO (so an
    // exposed app owns its own /health, /_ay/*, etc.). The DO is addressed by a
    // fixed internal /_visit path so a visitor can never reach the daemon leg
    // (which the DO accepts only on the /_daemon path the Worker alone sets).
    const exp = EXPOSURE_HOST.exec(host);
    if (exp) {
      const inner = new Request(new URL(`/_visit${url.pathname}${url.search}`, url), req);
      return env.EXPOSURES.get(env.EXPOSURES.idFromName(exp[1]!)).fetch(inner);
    }

    // The lab subdomain is served entirely out of the /lab asset directory.
    if (host === LAB_HOST) return labFetch(url, req, env);

    if (url.pathname === "/health") return new Response("ok\n");

    // Daemon leg of a port exposure: `ay expose` dials this on the apex (the id
    // rides the path). Reachable ONLY here — the DO trusts the /_daemon path,
    // which the Worker sets exclusively for this route, never for a visitor.
    const tun = /^\/_ay\/tunnel\/(x[a-z0-9]{7,31})$/.exec(url.pathname);
    if (tun && req.headers.get("Upgrade") === "websocket") {
      const inner = new Request(new URL("/_daemon", url), req);
      return env.EXPOSURES.get(env.EXPOSURES.idFromName(tun[1]!)).fetch(inner);
    }

    // Apex → lab redirects. /blog/* is the old home of the write-ups; /lab/* is
    // the raw asset path the lab host reads from internally (ASSETS.fetch is not
    // routed through this Worker, so redirecting the public path can't loop).
    // Both 301 so the lab subdomain is the single canonical origin.
    if (url.pathname === "/blog" || url.pathname.startsWith("/blog/")) {
      const slug = url.pathname.replace(/^\/blog\/?/, "").split("/")[0] ?? "";
      // hasOwn, not `?? ""`: a bare object literal inherits Object.prototype, so
      // /blog/constructor would otherwise redirect to a stringified builtin.
      const to = Object.hasOwn(BLOG_MOVED, slug) ? BLOG_MOVED[slug] : "";
      return Response.redirect(`${LAB_ORIGIN}/${to}${url.search}`, 301);
    }
    if (url.pathname === "/lab" || url.pathname.startsWith("/lab/")) {
      // Collapse duplicate slashes here too: /lab//evil.com/ would otherwise hand
      // the lab host a protocol-relative path (see labFetch for why that matters).
      const rest = url.pathname.replace(/^\/lab\/?/, "/").replace(/\/{2,}/g, "/");
      return Response.redirect(`${LAB_ORIGIN}${rest}${url.search}`, 301);
    }

    // WebSocket to /<room> → signaling DO (this is the s.agent-yes.com path).
    const m = /^\/([A-Za-z0-9_-]{1,64})$/.exec(url.pathname);
    if (m && req.headers.get("Upgrade") === "websocket") {
      const id = env.ROOMS.idFromName(m[1]!);
      return env.ROOMS.get(id).fetch(req);
    }

    // Everything else → the static console UI (agent-yes.com).
    return withDocHeaders(await env.ASSETS.fetch(req));
  },
};

type Attach = { authed: boolean; role?: "host" | "client"; peer?: string; mesh?: boolean };

export class Room {
  constructor(private state: DurableObjectState) {
    // Answer the host's 20s keepalive ping from the runtime itself, so a ping on
    // a hibernated socket is pong'd WITHOUT waking the DO. Waking on every ping
    // would keep the DO out of hibernation and accrue billable duration — the
    // exact failure mode that drove ~99.9% of the account's DO time on the
    // codehost wire. setWebSocketAutoResponse persists across hibernation and
    // applies to all (current + future) accepted sockets. The inline ping
    // handler in webSocketMessage stays only as a fallback for a non-exact ping.
    this.state.setWebSocketAutoResponse(new WebSocketRequestResponsePair(PING, PONG));
  }

  async fetch(req: Request): Promise<Response> {
    if (req.headers.get("Upgrade") !== "websocket") {
      return new Response("expected websocket", { status: 426 });
    }
    // The subprotocol only marks our protocol version — NO token here. (The token
    // is sent in the first message instead: Bun's WS client mangles long
    // subprotocol values, and keeping it out of the handshake also avoids any
    // chance of it reaching request logs.)
    const offered = (req.headers.get("Sec-WebSocket-Protocol") ?? "")
      .split(",")
      .map((s) => s.trim());
    if (offered[0] && offered[0] !== SUBPROTO) {
      return new Response("bad subprotocol", { status: 400 });
    }

    const { 0: client, 1: server } = new WebSocketPair();
    this.state.acceptWebSocket(server);
    server.serializeAttachment({ authed: false } satisfies Attach);

    return new Response(null, {
      status: 101,
      webSocket: client,
      headers: { "Sec-WebSocket-Protocol": SUBPROTO },
    });
  }

  async webSocketMessage(ws: WebSocket, raw: string): Promise<void> {
    const self = ws.deserializeAttachment() as Attach;
    let msg: Record<string, unknown>;
    try {
      msg = JSON.parse(raw);
    } catch {
      return; // ignore non-JSON
    }

    if (!self.authed) {
      // First message must be the hello that carries role + token (+ optional mesh flag).
      if (msg.type !== "hello") return ws.close(1008, "expected hello");
      const role: "host" | "client" = msg.role === "host" ? "host" : "client";
      const token = String(msg.token ?? "");
      const proto = Number(msg.v ?? 1); // protocol generation (v2 = e2e)
      // Mesh rooms (ay ch channels) are symmetric — every peer relays to every
      // other peer, no single host. The mode is TOFU-pinned on room open, so the
      // star (share) and mesh (channels) wires can never mix within one room and
      // the existing host↔client path stays byte-identical for non-mesh clients.
      const mesh = msg.mesh === true;
      const stored = await this.state.storage.get<string>("token");
      const storedProto = (await this.state.storage.get<number>("proto")) ?? 1;
      const storedMesh = (await this.state.storage.get<boolean>("mesh")) ?? false;
      if (stored === undefined) {
        // Opening the room: a star room must be opened by its host; a mesh room
        // is opened by whoever arrives first (all peers are equal).
        if (!mesh && role !== "host") return ws.close(1008, "room not open");
        await this.state.storage.put("token", token);
        await this.state.storage.put("proto", proto);
        await this.state.storage.put("mesh", mesh);
      } else {
        if (stored !== token) return ws.close(1008, "forbidden"); // token never echoed
        if (storedProto !== proto) return ws.close(1008, "protocol mismatch");
        if (storedMesh !== mesh) return ws.close(1008, "room mode mismatch");
      }
      const peer = mesh || role === "client" ? crypto.randomUUID().slice(0, 8) : "host";
      // In a mesh, tell the newcomer who is already here (roster) and announce it
      // to everyone else, so both sides can open a direct DataChannel. Who sends
      // the offer (initiator = lower peer id) is decided client-side to avoid glare.
      const roster = mesh ? this.peers(ws) : undefined;
      // hostPresent lets a client FAST-FAIL a previously-opened star room whose
      // host has since left: the room's token is still stored (so we don't close
      // it as "room not open" above), but no live host socket remains to answer
      // with an offer — without this the client waits the full 8s connect timeout
      // (rtc.js) for an offer that never comes, and a viewer with N dead saved
      // rooms pays N×8s of reconnect churn on every open. Only meaningful for a
      // non-mesh client; omitted (undefined → dropped by JSON) for host/mesh.
      const hostPresent = mesh || role === "host" ? undefined : this.hasHost();
      ws.serializeAttachment({ authed: true, role, peer, mesh } satisfies Attach);
      ws.send(
        JSON.stringify({ type: "welcome", peer, role, v: proto, mesh, peers: roster, hostPresent }),
      );
      if (mesh) this.broadcast(ws, { type: "peer-join", peer });
      else if (role === "client") this.toHost({ type: "peer-join", peer });
      return;
    }

    // Heartbeat fallback: exact "{"type":"ping"}" frames are normally answered
    // by setWebSocketAutoResponse (see constructor) and never reach here, so the
    // DO stays hibernated. This only runs for a ping that didn't match the pair
    // byte-for-byte; answer it directly rather than relay it onward.
    if (msg.type === "ping") return void ws.send(PONG);

    if (self.mesh) {
      // Symmetric relay: every message carries a `to`; forward it to that peer.
      msg.from = self.peer; // tag so the recipient can reply/route back
      const to = typeof msg.to === "string" ? msg.to : "";
      if (to) this.toPeer(to, msg);
      return;
    }
    if (self.role === "client") {
      msg.from = self.peer; // tag so the host can route the reply back
      this.toHost(msg);
    } else {
      const to = typeof msg.to === "string" ? msg.to : "";
      if (to) this.toPeer(to, msg);
    }
  }

  webSocketClose(ws: WebSocket): void {
    const self = ws.deserializeAttachment() as Attach;
    if (!self.authed) return;
    if (self.mesh) this.broadcast(ws, { type: "peer-leave", peer: self.peer });
    else if (self.role === "client") this.toHost({ type: "peer-leave", peer: self.peer });
  }

  // Is a live host peer currently attached? (star rooms only.) Used to tell a
  // joining client to fast-fail a room whose host has left, instead of waiting
  // for an offer that will never arrive. A dead host that dropped uncleanly may
  // linger briefly until the runtime reaps its socket — a transient false
  // "present" just means one more 8s wait + backoff, never a wrong connection.
  private hasHost(): boolean {
    for (const s of this.state.getWebSockets()) {
      const a = s.deserializeAttachment() as Attach | null;
      if (a?.authed && a.role === "host") return true;
    }
    return false;
  }

  // Role isn't a hibernation tag (it's only known after the hello), so route by
  // walking the sockets and reading each one's attachment.
  private toHost(obj: unknown): void {
    const data = JSON.stringify(obj);
    for (const s of this.state.getWebSockets()) {
      const a = s.deserializeAttachment() as Attach | null;
      if (a?.authed && a.role === "host") s.send(data);
    }
  }
  private toPeer(peer: string, obj: unknown): void {
    const data = JSON.stringify(obj);
    for (const s of this.state.getWebSockets()) {
      const a = s.deserializeAttachment() as Attach | null;
      if (a?.authed && a.peer === peer) s.send(data);
    }
  }

  // Mesh helpers: fan a frame out to every OTHER authed peer, and list the peers
  // currently in the room (excluding `except` — the newcomer receiving the roster).
  private broadcast(except: WebSocket, obj: unknown): void {
    const data = JSON.stringify(obj);
    for (const s of this.state.getWebSockets()) {
      if (s === except) continue;
      const a = s.deserializeAttachment() as Attach | null;
      if (a?.authed) s.send(data);
    }
  }
  private peers(except: WebSocket): string[] {
    const out: string[] = [];
    for (const s of this.state.getWebSockets()) {
      if (s === except) continue;
      const a = s.deserializeAttachment() as Attach | null;
      if (a?.authed && a.peer) out.push(a.peer);
    }
    return out;
  }
}
